#!/bin/bash
set -euo pipefail

exec 3>&1           # Make stdout available as fd 3 for the result
exec 1>&2           # Redirect all output to stderr for logging

# Concourse tell us what should be our working dir
cd "$1"

# INPUT *******************************************************************
jq -M -S . <&0 | tee /tmp/input.json >/dev/null    # tee redirects to a file.

source=$(jq -r '.source' < /tmp/input.json)
uri=$(jq -r '.source.uri' < /tmp/input.json)
ref=$(jq -r '.version.ref // empty' < /tmp/input.json)

# IN **********************************************************************
git clone --no-checkout "${uri}" /tmp/repository
git -C /tmp/repository checkout "${ref}"

/opt/resource/scripts/gen-autopilot-pipeline.sh "/tmp/repository/" "${source}" > ./pipeline.yml

# OUTPUT ******************************************************************
json_output='{ "version":{ "ref": "'$ref'" }}'

jq -n "$json_output" >&3
