#!/bin/bash
set -euo pipefail

exec 3>&1           # Make stdout available as fd 3 for the result
exec 1>&2           # Redirect all output to stderr for logging

# Concourse tell us what should be our working dir
cd "$1"

# INPUT *******************************************************************
jq -M -S . <&0 | tee /tmp/input.json >/dev/null    # tee redirects to a file.

# OUT *********************************************************************
json_output='{}' # NO-OP

# OUTPUT **************************************************************************************
jq -n "$json_output" >&3
